### ISSUE TITLE
Any plans for provide some common Handlers?

### ISSUE THREAD

**Issue by geovanisouza92** [garethr/serf-master#1]
Hi @garethr, this project is a nice work. Congratulations!

There is any plans to provide common Handlers, like PostgreSQL, MySQL, Django, Nginx, Apache, Node.js, etc.?

**Comment by garethr** [comment]
One of the advantages (as I see it) of taking a much more standardized approach to writing handlers is sharing and packaging up useful handlers. I had probably thought these best to live in separate modules (eg serf_master_nginx) rather than as part of serf_master, but they would probably subclass SerfHandler. If you create a handler do let me know as listing them in the README would be great.
